name: Retrieve Apex Classes

on:
  workflow_dispatch:

jobs:
  retrieve-apex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to Salesforce via Auth URL
      run: |
        echo "force://PlatformCLI::5Aep861ZcIr522KYf5_dJGHP0DoGwPBqKHfaF8wtsscbXS_bhKNGNaI7R6VxJStzX6TthdzxX_hOsnosN" > sfdx-auth-url.txt
        sfdx auth:sfdxurl:store -f sfdx-auth-url.txt -a eeg

    - name: Retrieve Apex Classes
      run: |
        sfdx force:source:retrieve -x manifest/package.xml -u eeg

    - name: Upload Retrieved Classes
      uses: actions/upload-artifact@v4.4.1
      with:
        name: apex-classes
        path: force-app
