name: Retrieve Apex Classes

on:
  workflow_dispatch:

jobs:
  retrieve-apex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global

    - name: Authenticate to Salesforce via Auth URL
      run: |
        echo "force://PlatformCLI::5Aep861ZcIr522KYf5_dJGHP0DoGwPBqKHfaF8wtsscbXS_bhKNGNaI7R6VxJStzX6TthdzxX_hOsnosN" > sfdx-auth-url.txt
        sfdx auth:sfdxurl:store -f sfdx-auth-url.txt -a myOrg

    - name: Retrieve Apex Classes
      run: |
        mkdir -p retrieve
        echo "{
          \"manifest\": {
            \"types\": [
              {
                \"members\": \"ZscalerSKOUtility\", 
                \"name\": \"ApexClass\"
              }
            ],
            \"version\": \"59.0\"
          }
        }" > package.xml
        sfdx force:source:retrieve -x package.xml -u myOrg -r retrieve

    - name: Upload Retrieved Classes
      uses: actions/upload-artifact@v3.1.4
      with:
        name: apex-classes
        path: retrieve
