name: Retrieve Apex Classes with Python

on:
  workflow_dispatch:

jobs:
  retrieve-apex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Node.js (for sfdx)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Salesforce CLI
      run: npm install -g sfdx-cli

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Authenticate & Retrieve Apex via Python script
      env:
        SFDX_AUTH_URL: 'force://PlatformCLI::5Aep861ZcIr522KYf5_dJGHP0DoGwPBqKHfaF8wtsscbXS_bhKNGNaI7R6VxJStzX6TthdzxX_hOsnosNYlITIG@eeginc--c1.sandbox.my.salesforce.com'
      run: python retrieve_apex.py

    - name: Upload Retrieved Apex Classes
      uses: actions/upload-artifact@v4
      with:
        name: apex-classes
        path: force-app
