name: Updated Track Extrack

on:
  push:
    paths:
      - 'track.zip'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract ZIP file
        run: |
          mkdir extracted
          unzip track.zip -d extracted

      - name: Move extracted files
        run: |
          mkdir -p destination
          cp -r extracted/* destination/

      - name: Commit and push changes
        env:
          TOKEN: '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'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add destination
          git commit -m "Extracted ZIP and moved contents to destination" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
